vich_uploader:
    db_driver: orm

    mappings:
       posts:
           uri_prefix: '%post_attachments%'
           upload_destination: '%kernel.project_dir%/public%post_attachments%'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: true
           delete_on_remove: true 
       paragraphs:
           uri_prefix: '%post_attachments%'
           upload_destination: '%kernel.project_dir%/public%post_attachments%'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: true
           delete_on_remove: true 