controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

notFound_index:
    path: /{req}
    defaults: { _controller: App\Controller\NotFoundController::index }
    requirements:
        req: ".*"